name:    investments-info
version: "0.0.0"

dependencies:

# Due to a bug in GHC 8.0.1, we block its usage
# See: https://ghc.haskell.org/trac/ghc/ticket/12130
- base >=4.8.2.0 && <4.9 || >=4.9.1.0 && <5

# version 1.0 had a bug in reexporting Handler, causing trouble
- classy-prelude-yesod >=0.10.2 && <1.0 || >=1.1

- yesod >=1.4.3 && <1.5
- yesod-core >=1.4.30 && <1.5
- yesod-auth >=1.4.0 && <1.5
- yesod-static >=1.4.0.3 && <1.6
- yesod-form >=1.4.0 && <1.5
- classy-prelude >=0.10.2
- classy-prelude-conduit >=0.10.2
- bytestring >=0.9 && <0.11
- text >=0.11 && <2.0
- persistent >=2.0 && <2.8
- persistent-sqlite >2.6.0 && <= 2.6.2
- persistent-template >=2.0 && <2.8
- template-haskell
- shakespeare >=2.0 && <2.1
- hjsmin >=0.1 && <0.3
- monad-control >=0.3 && <1.1
- wai-extra >=3.0 && <3.1
- yaml >=0.8 && <0.9
- directory >=1.1 && <1.4
- warp >=3.0 && <3.3
- warp-tls > 3.2.0 && <= 3.2.4
- data-default
- aeson >=0.6 && <1.3
- conduit >=1.0 && <2.0
- monad-logger >=0.3 && <0.4
- fast-logger >=2.2 && <2.5
- wai-logger >=2.2 && <2.4
- file-embed
- safe
- unordered-containers
- containers
- vector
- time
- case-insensitive
- wai
- generic-deriving > 1.11.0 && <= 1.11.2
- cookie
- financial-news-scraper
- esqueleto
- hashable
- transformers >= 0.4 && < 0.6
- safe >= 0.3 && < 0.4
- errors
- bcrypt >= 0.0.8      && < 0.0.11
- uuid                          >= 1.3        && < 1.4
- uuid-types                    >= 1.0        && < 2.0
- lens
- conduit
- conduit-extra
- csv-conduit >= 0.6.7
- vector
- utf8-string >= 1.0.0.0
- split >= 0.2.3.1
- wreq
- regex-pcre-builtin
- utf8-string
- csv
- mtl >= 2.2.1
- http-conduit >=2.1 && <2.4
- http-client >= 0.5.6.0
- http-client-tls >= 0.3.4
- exceptions >= 0.8.3
- pretty-show >= 1.6.12


default-extensions:
  - NoImplicitPrelude
  - FlexibleContexts
  - QuasiQuotes
  - TemplateHaskell
  - ConstraintKinds
  - GADTs
  - RankNTypes
  - OverloadedStrings
  - GeneralizedNewtypeDeriving

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2

# Runnable executable for our application
executables:
  investments-info:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - investments-info
    when:
    - condition: flag(library-only)
      buildable: false

# Test suite
tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - yesod-test
    - hspec
    - investments-info
    - microlens

# Define flags used by "yesod devel" to make compilation faster
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
