resolver: lts-12.25

packages:
  - '.'
  - location:
      git: git@github.com:v0d1ch/financial-news-scraper
      commit: 703bae2c646b580787b0ffe408bee8374e9c82e2
    extra-dep: true
  - location:
      git: git@github.com:bitemyapp/esqueleto.git
      commit: 5f98e7b25334ec120125ca84ef647d5c4575a010
    extra-dep: true

#docker:
# enable: true
