resolver: lts-9.4

packages:
- '.'
- location:
    git: https://github.com/v0d1ch/financial-news-scraper.git
    commit: 8c11f4c76b55a143a8bf935fda2f4866f31ab551

  extra-dep: false

- location:
    git: https://github.com/v0d1ch/MailchimpSimple.git
    commit: ca789a8c2997178ca98f3728bc4b4ffb4fb702cd

  extra-dep: false

- location:
    git: https://github.com/qtests/yadata.git
    commit: 359fbf81144d83df6152392783032bfa441d4420

  extra-dep: false

extra-deps:
  - wreq-0.5.1.0
  - scalpel-core-0.5.1
  - scalpel-0.5.1
  - webdriver-0.8.5
  - aeson-lens-0.5.0.0
  - Chart-diagrams-1.8.2

flags: {}

extra-package-dbs: []

#docker:
# enable: true
