resolver: lts-13.0

packages:
  - '.'
  - location:
      git: https://github.com/bitemyapp/esqueleto.git
      commit: 5f98e7b25334ec120125ca84ef647d5c4575a010
    extra-dep: true
  - location:
      git: https://github.com/v0d1ch/financial-news-scraper.git
      commit: 404330f574caa2cf69fba6b6916d6502cecc421e
    extra-dep: true

# docker:
#  enable: true
