resolver: lts-10.4

packages:
  - '.'

extra-deps:
  - wreq-0.5.1.0
  - scalpel-core-0.5.1
  - scalpel-0.5.1
  - webdriver-0.8.5
  - aeson-lens-0.5.0.0
  - Chart-diagrams-1.8.2
  - amazonka-core-1.5.0
  - amazonka-1.5.0
  - amazonka-ses-1.5.0
  - bcrypt-0.0.10
  - generic-deriving-1.11.2
  - persistent-postgresql-2.6.1
  - persistent-sqlite-2.6.2
  - word24-1.0.7
  - MailchimpSimple
  - news-fetcher
  - newsletter
  - yadata
  - blaze-0.0.2

#docker:
# enable: true
