# resolver: lts-9.4
resolver: lts-8.4

packages:
- '.'
- location:
    git: https://github.com/qtests/yadata.git
    commit: aed05783630226c183f2d07eb5e0ab22ff1dd95d
  extra-dep: false
- location:
    git: https://github.com/v0d1ch/financial-news-scraper.git
    commit: 8c11f4c76b55a143a8bf935fda2f4866f31ab551

  extra-dep: false


extra-deps:
  - wreq-0.5.1.0
  - scalpel-core-0.5.1
  - scalpel-0.5.1
  - webdriver-0.8.5

flags: {}

extra-package-dbs: []

# docker:
#   enable: true
