static-dir:     "_env:STATIC_DIR:static"
host:           "_env:HOST:a4" # any IPv4 host
port:           "_env:PORT:5000" # NB: The port `yesod devel` uses is distinct from this value. Set the `yesod devel` port from the command line.
ip-from-header: "_env:IP_FROM_HEADER:false"

approot:        "_env:APPROOT:http://localhost:5000"

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
# detailed-logging: false
# should-log-all: false
# reload-templates: false
# mutable-static: false
# skip-combining: false
# auth-dummy-login : false


# local db settings
database:


  user:     "_env:PGUSER:postgres"
  password: "_env:PGPASS:postgres"
  host:     "_env:PGHOST:localhost"
  port:     "_env:PGPORT:5432"
  database: "_env:PGDATABASE:ii"
  poolsize: "_env:PGPOOLSIZE:10"

aws-ses-access-key: aaaaaaaaaaaa
aws-ses-secret-key: aaaaaaaaaaaa

aws-access-key:  aaaaaaaaaaaaaaa
aws-secret-key:  aaaaaaaaaaaaaaa
mailchimp-api-key: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

# this is used in the IO db runner
dbuser:     "postgres"
dbpassword: "postgres"
dbhost:     "localhost"
dbport:     "5432"
dbdatabase: "ii"


admins:
  [
   { aemail: brutallesale@gmail.com, apassword: sasa },
   { aemail: vpleta@gmx.ch, apassword: vidas }
  ]


copyright: Investments-info 2018
analytics: UA-109838792-1
