static-dir:     "_env:STATIC_DIR:static"
host:           "_env:HOST:a4" # any IPv4 host
port:           "_env:PORT:3000" # NB: The port `yesod devel` uses is distinct from this value. Set the `yesod devel` port from the command line.
ip-from-header: "_env:IP_FROM_HEADER:false"

#approot:        "_env:APPROOT:http://localhost:3000"

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
# detailed-logging: false
# should-log-all: false
# reload-templates: false
# mutable-static: false
# skip-combining: false
# auth-dummy-login : false
database:
  user:     "_env:PGUSER:aaaaaaaaaaa"
  password: "_env:PGPASS:aaaaaaaaaaa"
  host:     "_env:PGHOST:aaaaaaaaaa"
  port:     "_env:PGPORT:11111"
  database: "_env:PGDATABASE:aaaaaaaaaaaa"
  poolsize: "_env:PGPOOLSIZE:10"

# this is used in the IO db runner
dbuser:     "aaaaaaaaaaa"
dbpassword: "aaaaaaaaaaa"
dbhost:     "aaaaaaaaaaa"
dbport:     "aaaaaaaaaaa"
dbdatabase: "aaaaaaaaaaa"

aws-ses-access-key: aaaaaaaaaaaa
aws-ses-secret-key: aaaaaaaaaaaa

aws-access-key:  aaaaaaaaaaaaaaa
aws-secret-key:  aaaaaaaaaaaaaaa
mailchimp-api-key: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 

admins:
  [
   {aemail: aaaaaaaaaa, apassword: aaaaaaaaa},
   {aemail: aaaaaaaaaa, apassword: aaaaaaaa}
  ]

copyright: Investments-info 2017
analytics: aaaaaaaaaaaa
